# Base config
title: Jonathan Gruber
author: Jonathan Gruber
email: hi@grubersjoe.de
description: Website von Jonathan Gruber - Webentwickler in Leipzig
baseurl: ""

# Defaults
defaults:
  -
    values:
      layout: "post"

# Markdown config
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

include:
  - _pages

exclude:
    - README.md
    - LICENSE
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - node_modules
    - package.json
    - package-lock.json
    - npm-debug.log
    - src

# Plugins
plugins:
    - jekyll-archives
    - jekyll-feed
#    - jekyll-language-plugin

# Plugin config
jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/blog/:name/'

# language_data: data.lang.%%
# language_includes_dir: _i18n
